name: deploy reactjs application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Create .env File
        run: |
          echo "VITE_APP_WEATHER_URL = https://api.openweathermap.org/data/2.5/weather?q=Cambridge,uk&units=metric&appid=" >> .env
          echo "VITE_APP_WEATHER_API = 83581cb6f6a7f8ba2d9f33fb7898748e" >> .env
          echo "VITE_APP_BASEURL = http://${{secrets.SERVER_IP}}:5000/" >> .env
          echo "VITE_APP_NODEENV = production" >> .env
          echo "VITE_APP_GLOBAL_URL = news/global" >> .env
          echo "VITE_APP_LOCAL_URL = news/local" >> .env

      - name: Setting up the node environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Build react app
        run: npm run build

      - name: Login to Docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/cambridgeappfrontendimage:latest .

      - name: Push the image to the dockerhub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/cambridgeappfrontendimage:latest

      - name: run docker container
        run: |
          docker stop ${{ secrets.DOCKER_USERNAME }}/cambridgeappfrontendimage || true
          docker rm ${{ secrets.DOCKER_USERNAME }}/cambridgeappfrontendimage || true
      - name: Delete all unsued images
        run: |
          docker image prune -a -f

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy Docker image
        run: |
          docker pull ${{secrets.DOCKER_USERNAME}}/cambridgeappfrontendimage:latest
          docker run -d -p 80:80 --name cambridgeappfrontendcontainer ${{ secrets.DOCKER_USERNAME }}/cambridgeappfrontendimage
